<?php

namespace Database\Seeders;

use App\Models\ExhibitionElement;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $adminEmail = env('ADMIN_EMAIL', 'admin@communiquer.local');
        $adminPassword = env('ADMIN_PASSWORD', 'admin12345');

        User::query()->updateOrCreate([
            'email' => $adminEmail,
        ], [
            'name' => 'Administrator',
            'password' => Hash::make($adminPassword),
            'email_verified_at' => now(),
            'is_admin' => true,
        ]);

        User::query()->updateOrCreate([
            'email' => 'test@example.com',
        ], [
            'name' => 'Test User',
            'password' => Hash::make('password'),
            'email_verified_at' => now(),
            'is_admin' => false,
        ]);

        $elements = [
            [
                'page' => 'home',
                'section' => 'hero_meta',
                'title' => 'Date',
                'content' => 'June 8-14, 2026',
                'secondary_content' => '10:00 to 16:00 daily',
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section' => 'hero_meta',
                'title' => 'Venue',
                'content' => 'ExCel London Hotel',
                'secondary_content' => 'London, United Kingdom',
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section' => 'hero_meta',
                'title' => 'Organizer',
                'content' => 'Francois Pinault',
                'secondary_content' => 'Global cultural patron',
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section' => 'highlight',
                'title' => 'Clear event information',
                'content' => 'Dates, venue and participation terms are available from the first screen.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section' => 'highlight',
                'title' => 'Professional communication',
                'content' => 'Press, media and legal pages support international trust and transparency.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section' => 'highlight',
                'title' => 'Exhibitor support',
                'content' => 'Transport, accommodation, customs handling and insured artwork logistics are included.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section' => 'mission_cards',
                'title' => 'Concept',
                'content' => 'Alliance Expo Monde / Global Alliance Exhibition is a curated international event focused on artists who are talented but still underexposed in mainstream art circuits.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section' => 'mission_cards',
                'title' => 'Theme',
                'content' => '"Visibility Without Borders": connecting creators, collectors, and cultural institutions around powerful emerging voices from multiple countries.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section' => 'mission_cards',
                'title' => 'Vision',
                'content' => 'Build a recurring global platform where young and lesser-known artists can access serious market opportunities and long-term international recognition.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section' => 'mission_cards',
                'title' => 'Objectives',
                'content' => 'Promote hidden artistic talent, support youth integration in the art world, and provide credible international exposure through a structured exhibition ecosystem.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section' => 'biography',
                'title' => 'Francois Pinault',
                'content' => 'Francois Pinault (born August 21, 1936, Rennes) is a French businessman and art collector, founder of the luxury group Kering.',
                'secondary_content' => null,
                'extra_content' => 'A major patron of contemporary art, he established renowned exhibition spaces in Venice and Paris.',
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'artists',
                'section' => 'artist_cards',
                'title' => 'Amara N\'Diaye',
                'content' => 'Works at the intersection of textile memory and abstract portraiture.',
                'secondary_content' => 'Country: Senegal',
                'extra_content' => 'Exhibited works: "Threads of Silence", "DakArt Echoes"',
                'image_path' => 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'Portrait of Amara N\'Diaye',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'artists',
                'section' => 'artist_cards',
                'title' => 'Lucia Ferraro',
                'content' => 'Contemporary figurative painter exploring migration and belonging.',
                'secondary_content' => 'Country: Italy',
                'extra_content' => 'Exhibited works: "Transit Light", "Shoreline Fragments"',
                'image_path' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'Portrait of Lucia Ferraro',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'artists',
                'section' => 'artist_cards',
                'title' => 'Mateo Alvarez',
                'content' => 'Uses layered acrylic and collage to map urban memory.',
                'secondary_content' => 'Country: Colombia',
                'extra_content' => 'Exhibited works: "Concrete Rhythm", "Southbound Grid"',
                'image_path' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'Portrait of Mateo Alvarez',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'page' => 'venue',
                'section' => 'info_cards',
                'title' => 'Full address',
                'content' => 'ExCel London Hotel',
                'secondary_content' => 'Royal Victoria Dock, 1 Western Gateway',
                'extra_content' => 'London E16 1XL, United Kingdom',
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'venue',
                'section' => 'info_cards',
                'title' => 'Event schedule',
                'content' => 'June 8 to June 14, 2026',
                'secondary_content' => 'Open daily from 10:00 to 16:00',
                'extra_content' => 'Registration desk opens at 09:00',
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'venue',
                'section' => 'support_cards',
                'title' => 'Transport',
                'content' => 'Closest airports: London City Airport and Heathrow Airport. DLR and Elizabeth line connections are available for ExCel London.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'press',
                'section' => 'partner_cards',
                'title' => 'easyJet',
                'content' => 'Official transport partner for artist and cargo logistics.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'press',
                'section' => 'partner_cards',
                'title' => 'Ryanair',
                'content' => 'Official airline partner supporting international routing and handling.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'press',
                'section' => 'resource_cards',
                'title' => 'Press resources',
                'content' => null,
                'secondary_content' => null,
                'extra_content' => "Official event identity and partner references\nExhibition overview for editors and media desks\nContact channel for interviews and accreditation",
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'press',
                'section' => 'resource_cards',
                'title' => 'Downloadable documents',
                'content' => 'Access the official PDF communication package.',
                'secondary_content' => null,
                'extra_content' => null,
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page' => 'contact',
                'section' => 'channel_cards',
                'title' => 'Official channels',
                'content' => 'Email: pinault12art@gmail.com',
                'secondary_content' => 'WhatsApp: +44 7405 854019',
                'extra_content' => 'Partners: easyJet & Ryanair',
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page' => 'contact',
                'section' => 'terms_cards',
                'title' => 'Participation terms (summary)',
                'content' => null,
                'secondary_content' => null,
                'extra_content' => "Recommended max artwork size: 150 cm x 200 cm\nRecommended max weight: 50 kg\nCommission on sold artworks: 15%\nParticipation fee: 2000 EUR\nDamages are covered from boarding to exhibition end",
                'image_path' => null,
                'image_alt' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
        ];

        foreach ($elements as $element) {
            ExhibitionElement::query()->firstOrCreate([
                'page' => $element['page'],
                'section' => $element['section'],
                'sort_order' => $element['sort_order'],
                'title' => $element['title'],
            ], $element);
        }
    }
}
